### ISSUE TITLE
add instructions on instantiating templates?

### ISSUE THREAD

**Issue by JStatnekov** [acharluk/Fenix#2]
The workflow is straightforward (install Fenix, add repo of templates, instantiate project template) but I don't see a way to do the last step. When I open Fenix (using the Open Fenix button in the upper left of the Fenix view) I suspect there should be an info window with instructions but I'm just getting a blank tab (see screenshot). I have looked through the command pallet options and don't see any that might expose the template instantiation feature. Is the Fenix main page supposed to be empty and are there instructions for instantiating project templates?

![Screenshot from 2020-07-18 06-32-13](https://user-images.githubusercontent.com/4362188/87853716-4e87fe00-c8c1-11ea-9dca-f447b1f32d1d.png)

**Comment by acharluk** [comment]
That page should show a window like the one in this screenshot:
![image](https://user-images.githubusercontent.com/5154281/87854990-ca139a80-c915-11ea-8136-5a9c5a75fb15.png)

I develop on Windows most of the time, so it's posible that something is breaking it on some Linux distros. It would be really helpful for me to know what OS, VSCode version and maybe even hardware you are using to fix this bug 😉.

**Comment by acharluk** [comment]
I have tinkered with it for a few minutes and it seems to be a problem with the latest version of VSCode (you can see in my earlier screenshot that I didn't have updated yet).

I will try to fix it and push an update as soon as I can. Thank you for the issue!

**Comment by JStatnekov** [comment]
Thank you for writing this and your quick response!

This seems like it is a very useful plugin and I suspect the only reason it hasn't become more popular than the "easy c++ projects" predecessor is because of this difficulty in getting started.

Here is the info from VSCode (my OS is actually Ubuntu 20.04LTS):

- Version: 1.47.1
- Commit: 485c41f9460bdb830c4da12c102daff275415b53
- Date: 2020-07-14T00:13:57.513Z
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Linux x64 5.4.0-40-generic snap

**Comment by acharluk** [comment]
I've managed to get it working again, even though it is a temporary fix. I'll push the update later today! 😀

![image](https://user-images.githubusercontent.com/5154281/88266834-2e48ac80-ccd0-11ea-98d0-379486387f96.png)

**Comment by acharluk** [comment]
Version 1.1.5 of Fenix should be now available, please try it out and check if it loads correctly @JStatnekov  :)
